### ISSUE TITLE
error while trying to build glava

### ISSUE THREAD

**Issue by Code-sleep-repeat** [jarcode-foss/glava#134]
Hi there!
I'm trying to build glava but meson gives me an error, see console output below:

```[justin@justins-pc Downloads]$ cd glava/
[justin@justins-pc glava]$ meson build --prefix /usr
The Meson build system
Version: 0.51.2
Source dir: /home/justin/Downloads/glava
Build dir: /home/justin/Downloads/glava/build
Build type: native build
Project name: glava
Project version: v1.6.3-87-g3cc5e22
C compiler for the host machine: cc (gcc 9.1.0 "cc (GCC) 9.1.0")
C++ compiler for the host machine: c++ (gcc 9.1.0 "c++ (GCC) 9.1.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Run-time dependency threads found: YES 
Library pulse found: YES
Library pulse-simple found: YES
Library dl found: YES
Library m found: YES
Library X11 found: YES
Library Xext found: YES
Library Xrender found: YES
Library dl found: YES
Dependency threads found: YES (cached)
Library GL found: YES
Library X11 found: YES

meson.build:184:2: ERROR: C library 'obs' not found

A full log can be found at /home/justin/Downloads/glava/build/meson-logs/meson-log.txt

```

Going to the log mentioned in the error I find this:
[https://pastebin.com/WixacSVe](https://pastebin.com/WixacSVe)

**Comment by jarcode-foss** [comment]
From the readme:

> Additional compile time requirements:
>
>    * Meson
>    * **OBS (disable with `-Ddisable-obs=true`)**

GLava needs OBS available at compile time to build its OBS plugin (but does not require it at runtime unless using the plugin itself). If you don't care about rendering directly to an OBS scene, just disable it.

**Comment by Code-sleep-repeat** [comment]
even when passing this command it gives the same error

**Comment by jarcode-foss** [comment]
@Code-sleep-repeat relevant line: https://github.com/jarcode-foss/glava/blob/master/meson.build#L183

Meson should not evaluate anything related to OBS if that parameter is passed. Make sure you are updated from `master` or simply use a stable release instead.

Note that there will be semi-frequent changes to the build process as I pave out new features for the next release, so you will need to re-configure the build entirely if you are operating on an existing repository you cloned before pulling in new changes.

**Comment by kd4pba** [comment]
Same issue here, gave up after spending a few hours trying to figure this out.  The odd thing is I do in fact have OBS installed.

**Comment by Anyeos** [comment]
Yes, how to specify the real installed OBS? It need some dev? Maybe a symlink if you don't have a dev?

**Comment by Keeermalec** [comment]
From readme.md, here are the right dependencies for Ubuntu:

sudo apt install libgl1-mesa-dev libpulse0 libpulse-dev libxext6 libxext-dev libxrender-dev libxcomposite-dev liblua5.3-dev liblua5.3-0 lua-lgi lua-filesystem libobs0 libobs-dev meson build-essential gcc

(note: liblua5.3 edited to liblua5.3-0 for Ubuntu 20.02)

**Comment by julianPescobar** [comment]
You're supposed to pass the parameter like this:
`-Ddisable_obs=true`

**Comment by 5urpriser** [comment]
could be this: 
https://stackoverflow.com/questions/20616961/usr-bin-ld-cannot-find-no-such-file-or-directory
