### ISSUE TITLE
Increased documentation on --pipe usage

### ISSUE THREAD

**Issue by djtran** [jarcode-foss/glava#145]
I was looking into how I could try to setgeometry dynamically (docked vs undocked laptop setup) and was trying to wrangle with piping settings scraped from xrandr into rc.glsl. I ended up trying something like:

```
xrandr | grep "Screen 0" | tr "," "\n" | grep current | awk 'BEGIN {FS = " "} {print "width = " $2 "\n" "height = " $4 }' | glava --desktop --pipe=width:int --pipe=height:int
```

Where this example output is being piped into glava:
```
width = 3440
height = 1440
```

and my rc.glsl has this defined
```
#define WIDTH @width:1920
#define HEIGHT @height:1080
...
#request setgeometry 0 0 WIDTH HEIGHT
```

I get this response from X with exit code 1:

```
% <all of that xrandr processing> | glava --desktop --pipe=width:int --pipe=height:int                                                                                                                         ~
X Error of failed request:  BadValue (integer parameter out of range for operation)                                                                                                                               
  Major opcode of failed request:  1 (X_CreateWindow)
  Value in failed request:  0x0
  Serial number of failed request:  43
  Current serial number in output stream:  48                                                                                                                                                                     
[1] % 
```

Unsure if i'm misinterpreting how pipe could be used, may be very simple but I'm not familiar with glsl or macro usage as a whole.

**Comment by djtran** [comment]
I managed to get what I wanted via the `-r` option instead of by piping. Closing.

gist: https://gist.github.com/djtran/a62351e601a288ec33287af3ada37db4

**Comment by jarcode-foss** [comment]
The reason for this is that requests are evaluated at compile-time, but pipe bindings evaluate to a uniform (that can be set at runtime) primarily for use within shaders. Additionally, because of how GLSL preprocessing currently works, `#request` directive will not expand macro invocations within its arguments.

In the future I may add special binding targets for changing window background and geometry at runtime, since those have no reason to be constrained to compile-time.
