### ISSUE TITLE
OBS don't load the plugin

### ISSUE THREAD

**Issue by Lewatoto** [jarcode-foss/glava#153]
I compiled following the standar instructions on readme.md, but OBS don't show Glava in sources list, i installed OBS from RPM Fusion and i don't know how to confirm if this version is using EGL or GLFW.

My system specs:
>Operating System: Fedora 31
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.66.0
Qt Version: 5.13.2
Kernel Version: 5.4.17-200.fc31.x86_64
OS Type: 64-bit
Processors: 8 × AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx
Memory: 15.3 GiB of RAM

OBS log [https://pastebin.com/mK0UuVc1](https://pastebin.com/mK0UuVc1)

Glxinfo output:
> glxinfo | grep OpenGL
OpenGL vendor string: X.Org
OpenGL renderer string: AMD RAVEN (DRM 3.35.0, 5.4.17-200.fc31.x86_64, LLVM 9.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 19.2.8
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
OpenGL core profile extensions:
OpenGL version string: 4.5 (Compatibility Profile) Mesa 19.2.8
OpenGL shading language version string: 4.50
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile
OpenGL extensions:
OpenGL ES profile version string: OpenGL ES 3.2 Mesa 19.2.8
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
OpenGL ES profile extensions:

Don't know if something else is needed for debug.

**Comment by jarcode-foss** [comment]
I do not recommend using the OBS plugin at the moment since it is relying on particularly hacky code to render directly to the OBS scene, and a more version-independent solution is pending on some changes to OBS itself.

So naturally, using this plugin may compromise the stability of OBS itself.

Your problem is probably from not installing via meson. OBS plugins must be a shared library placed in `/usr/lib/obs-plugins`.

> i don't know how to confirm if this version is using EGL or GLFW

It's unlikely. I do not know of any distribution that currently compiles OBS with EGL support instead of GLX/GLFW.

**Comment by TheSamabo** [comment]
Hello
My OBS also wasn't showing the GLava plugin, only after i reinstalled OBS. But i have other issue with the plugin. The plugin gets loaded but when i try to add it to the scene it just crashes the whole OBS

OBS log:

> 00:23:01.731: ==== Startup complete ===============================================
> 00:23:01.733: All scene data cleared
> 00:23:01.733: ------------------------------------------------
> 00:23:01.734: pulse-input: Server name: 'pulseaudio 13.0'
> 00:23:01.735: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
> 00:23:01.735: pulse-input: Started recording from 'combined.monitor'
> 00:23:01.735: pulse-input: Server name: 'pulseaudio 13.0'
> 00:23:01.735: pulse-input: Audio format: s16le, 44100 Hz, 2 channels
> 00:23:01.735: pulse-input: Started recording from 'alsa_input.usb-BEHRINGER_C-1U-00.iec958-stereo'
> 00:23:01.736: xshm-input: Geometry 1920x1080 @ 0,0
> 00:23:01.754: Source ID 'qtwebkit-source' not found
> 00:23:01.754: Failed to create source 'alerts'!
> 00:23:02.296: adding 46 milliseconds of audio buffering, total audio buffering is now 46 milliseconds (source: Desktop Audio)
> 00:23:02.296: 
> 00:23:09.076: Initializing GLava OBS Plugin...
> 00:23:09.076: Updating GLava state
> 00:23:09.076: Waiting for GLava GL texture...

system:
OS: Manjaro Linux x86_64 
Kernel: 5.4.31-1-MANJARO 
DE: KDE plasma
WM: KWin
CPU: Ryzen 2700x
GPU: AMD RX 580
Mem: 16Gb
