### ISSUE TITLE
Bluetooth connected speaker doesnt give display

### ISSUE THREAD

**Issue by Hu4k3n** [jarcode-foss/glava#159]
After connecting to external bluetooth speaker we cannot see the display

**Comment by coderobe** [comment]
Needs more info...

**Comment by samirza692** [comment]
hello,
yesterday i install glava on arch kde plasma 5.20.5  and i am totally new  on linux i just copied and pasted command and after many tried i figure out that this one is correct for me "#request setgeometry 0 0 1367 760" in rc.glsl and somehow managed to work now its working perfectly but when i switching to externel speaker through bluetooth  the visualizer not showing and again when i enable laptop speaker visualizer is showing  there is sound  on both speaker  but not visualizer  while on bluetooth speaker
ws-887 is a bluetooth speaker and sound is there but not visualizer on screen  while using it
check the video  i uploaded here

https://user-images.githubusercontent.com/21076139/108196817-90bb3b80-713f-11eb-886d-81c9aa5d34db.mp4

sorry for my bad english
