### ISSUE TITLE
Remove FPS data in terminal?

### ISSUE THREAD

**Issue by vaskark** [jarcode-foss/glava#160]
I run glava in a script for pywal color changes. However, whenever I use pywal to switch a theme _in a terminal_ I'm always presented with a running list of FPS data.
Is there any way I can turn this off? Ctrl-c isn't stopping it. It's annoying to have to close the terminal and reopen everytime this happens.

Thanks.

Ubuntu 20.04
GLava (glava) v1.6.3-87-g3cc5e22 (stable, unix/fhs)

**Comment by ZaWertun** [comment]
You can remove FPS by editing `~/.config/glava/rc.glsl`,
Change line
```
#request setprintframes true
```
to
```
#request setprintframes false
```

**Comment by vaskark** [comment]
Thanks so much :)

**Comment by rhysperry111** [comment]
You should probably close this issue now :)

**Comment by vaskark** [comment]
Oops! Closed.
