### ISSUE TITLE
Modify the scaling of the visualizer? (Radial, similar...)

### ISSUE THREAD

**Issue by smolyoshino** [jarcode-foss/glava#164]
Hello, hope I'm not causing too much trouble. I recently discovered this and was wondering if there's any way to change the scaling of a visualizer. I'm a newbie to most of this. Running Pop!_OS 20.04.
![unknown](https://user-images.githubusercontent.com/22896890/83552607-057a1700-a4d8-11ea-9b92-2e777a1c67cc.png)

**Comment by Scrumplex** [comment]
You can edit the config file for the circle visualizer at `~/.config/glava/circle.glsl` The first property allows you to set the radius (`C_RADIUS`).

**Comment by Scrumplex** [comment]
If the configs does not exist, you can create them with `glava -C` or `glava --copy-config`

**Comment by smolyoshino** [comment]
Ah, okay, thanks!
