### ISSUE TITLE
meson.build:21:0: ERROR: C library 'pulse' not found

### ISSUE THREAD

**Issue by pipipear** [jarcode-foss/glava#182]
```
The Meson build system
Version: 0.53.2
Source dir: /home/n/Documents/glava
Build dir: /home/n/Documents/glava/reconfigure
Build type: native build
Project name: glava
Project version: v1.6.3-87-g3cc5e22
C compiler for the host machine: cc (gcc 9.3.0 "cc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C linker for the host machine: cc ld.bfd 2.34
C++ compiler for the host machine: c++ (gcc 9.3.0 "c++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0")
C++ linker for the host machine: c++ ld.bfd 2.34
Host machine cpu family: x86_64
Host machine cpu: x86_64
Run-time dependency threads found: YES

meson.build:21:0: ERROR: C library 'pulse' not found

A full log can be found at /home/n/Documents/glava/reconfigure/meson-logs/meson-log.txt
```
Trying to build produces the error `meson.build:21:0: ERROR: C library 'pulse' not found`.

**Comment by WeMakeMachines** [comment]
This report is quite old, I don't know if it's still relevant - but you can fix this by installing all the needed dependencies. I'm assuming you are using Ubuntu and Debian `sudo apt-get install libgl1-mesa-dev libpulse0 libpulse-dev libxext6 libxext-dev libxrender-dev libxcomposite-dev liblua5.3-dev liblua5.3 lua-lgi lua-filesystem libobs0 libobs-dev meson build-essential gcc `

I found this information in the README

**Comment by po7upanow** [comment]
thank you
