### ISSUE TITLE
Glava detecting mic input, not sound?

### ISSUE THREAD

**Issue by myrcury** [jarcode-foss/glava#186]
Hey, I just installed GLava on Ubuntu 20.04, and realized it was visualizing mic input, not audio output. Is there a way to fix this?

**Comment by myrcury** [comment]
Re-configured GLava, problem fixed itself, thanks!

**Comment by myrcury** [comment]
The problem reintroduced itself upon playing music on Spotify, and now is back to registering mic input instead of computer audio. Is it an issue with PulseAudio?

**Comment by gunqqer** [comment]
Bit late for this but have you tried checking pavucontrol's recording tab and making sure GLava is monitoring the correct monitor?

**Comment by GodBleak** [comment]
> Bit late for this but have you tried checking pavucontrol's recording tab and making sure GLava is monitoring the correct monitor?

This ^
However, I'll offer a bit more detail, if not for your benefit, for posterity.

1. If not already installed; install `pavucontrol` AKA PulseAudio Volume Control
2. Open PulseAudio Volume Control, navigate to the 'Input Devices' tab, at the bottom of the window change the 'show' drop-down to 'Monitors', 
3. You should see a (or a list of) monitor(s), for me, my monitor was muted. Unmuting it should do the trick.

If glava is still detecting the mic input;
1. Note the name of the monitor(mine is '_**Monitor** of Built-in Audio **Analog Stereo**_'), open terminal, and run `pacmd list-sources`.
2. Locate the matching monitor(for me that's _name: <alsa_output.pci-0000_00_1f.3.**analog-stereo.monitor**>_)
3. note the index(4, for me)
4. open `~/.config/glava/rc.glsl` and locate `#request setsource "auto"` change `auto` to the index of the monitor. So for me that line would be `#request setsource "4"`.
5. Save the configuration and restart glava
5. glava should now be working as expected. You can use the verbose output (`glava -v`) to ensure it picked up the change in audio source. You should see `Using audio source:  {index here}` in the output.

Should you have issues with PulseAudio check out [PulseAudio/Troubleshooting](https://wiki.archlinux.org/index.php/PulseAudio/Troubleshooting)

I hope this helped! Happy listening!

**Comment by myrcury** [comment]
That worked, thank you so much!
