### ISSUE TITLE
Readme.md and -Ddisable-obs

### ISSUE THREAD

**Issue by gaussandhisgun** [jarcode-foss/glava#190]
So, in readme.md stated that you should pass `-Ddisable-obs` to meson for disabling obs support. But it is actually `-Ddisable_obs`, with `_` instead of `-`. `-Ddisable-obs` is an unknown option.
![Снимок экрана_2021-03-04_23-09-30](https://user-images.githubusercontent.com/63512006/110023853-b438d580-7d3e-11eb-8df2-7cdd4ef0f89c.png)

**Comment by coderobe** [comment]
thanks for the hint! fixed
