### ISSUE TITLE
mirror image of the bars in glava.

### ISSUE THREAD

**Issue by kheshav-coder** [jarcode-foss/glava#194]
I would love to see the bars rise in both up and down directions, what I am trying to ask is is there a way to make the bars go both +y-axis and -y-axis directions?

**Comment by githtz** [comment]
You could use to instances of `glava` as suggested here:
https://github.com/jarcode-foss/glava/issues/187

**Comment by kheshav-coder** [comment]
can you please explain how to do it I don't clearly understand #187

**Comment by githtz** [comment]
You could try it like this. I guess there's a better way, probably.
```
cd ~/.config/glava
cp -H -r bars bars2
cp bars.glsl bars2.glsl
cp rc.glsl rc2.glsl
```

First edit rc.glsl, find and edit as you need it (replace *display_width_px* and *display_height_halfed_px* with numbers)
`#request setgeometry 0 0 display_width_px display_height_halfed_px`
For example if your screen is *1920x1080*
`#request setgeometry 0 0 1920 540`

Then edit rc2.glsl but now
`#request setgeometry 0 display_height_halfed_px display_width_px display_height_halfed_px`
For example 
`#request setgeometry 0 540 1920 540`
Also change the loaded module from
`#request mod bars`
to
`#request mod bars2`

Now update the *1.frag* file in *bars2*; change
`#include ":bars.glsl"`
to 
`#include ":bars2.glsl"`
Make sure to not edit anyting else.

Now edit *bars2.glsl*
change
`#define FLIP 0`
to
`#define FLIP 1`

I think that's about it. Try running two instances of *glava* in separate terminals like this:
`glava -e rc.glsl`
`glava -e rc2.glsl`

**Comment by kheshav-coder** [comment]
WOW !! thank you very much buddy I really appreciate your efforts. I tried it and it works just as I wanted !!! 👍👍😀😀
